# Production Docker Compose Configuration with Load Balancing
# This file extends docker-compose.yml with production-specific settings
services:
  app:
    # Scale configuration - override with: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --scale app=5
    deploy:
      mode: replicated
      replicas: 3  # Default to 3 replicas for load balancing
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.chatbot.service=app"
      - "com.chatbot.version=1.0"

  nginx:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.chatbot.service=nginx"
      - "com.chatbot.version=1.0"

